<?php
namespace backend\filters;

use yii\base\ActionFilter;
use yii\web\ForbiddenHttpException;

class RbacFilter extends ActionFilter{
    public function beforeAction($action)
    {
        //如果用户没有登录,引导用户登录
        if(\Yii::$app->user->getIsGuest()){
            return $action->controller->redirect(\Yii::$app->user->loginUrl);
        }
        if(!\Yii::$app->user->can($action->uniqueId)){
           // return false;
            throw new ForbiddenHttpException('对不起,你没有改执行权限');
        }
        //return false; //拦截
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}